Name:           ros-kinetic-robotis-op3-msgs
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS robotis_op3_msgs package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/robotis_op3_msgs
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-op3-action-module-msgs
Requires:       ros-kinetic-op3-offset-tuner-msgs
Requires:       ros-kinetic-op3-online-walking-module-msgs
Requires:       ros-kinetic-op3-walking-module-msgs
BuildRequires:  ros-kinetic-catkin

%description
ROS messages packages for the ROBOTIS OP3 (meta package)

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Mar 21 2018 Pyo <pyo@robotis.com> - 0.1.1-0
- Autogenerated by Bloom

* Fri Oct 27 2017 Pyo <pyo@robotis.com> - 0.1.0-0
- Autogenerated by Bloom

